# Generated by Django 3.0.3 on 2020-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(max_length=100, verbose_name='Text')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
    ]
